<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

	<ItemGroup>
		<Resource Include="Fonts\*.ttf" />
	</ItemGroup>
	
  <ItemGroup>
    <Compile Remove="Interfaces\**" />
    <EmbeddedResource Remove="Interfaces\**" />
    <None Remove="Interfaces\**" />
    <Page Remove="Interfaces\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Drawing.Common" Version="6.0.0" />
    <PackageReference Include="System.Runtime.InteropServices" Version="4.3.0" />
  </ItemGroup>

	<ItemGroup>
		<Folder Include="Fonts\" />
	</ItemGroup>

  <Import Project="..\Contellation.Custom.Controls\Contellation.Custom.Controls.projitems" Label="Shared" />

  <Import Project="..\Contellation.Custom.Converters\Contellation.Custom.Converters.projitems" Label="Shared" />

  <Import Project="..\Contellation.Custom.Enums\Contellation.Custom.Enums.projitems" Label="Shared" />

  <Import Project="..\Contellation.Custom.Extensions\Contellation.Custom.Extensions.projitems" Label="Shared" />

  <Import Project="..\Contellation.Custom.Events\Contellation.Custom.Events.projitems" Label="Shared" />

  <Import Project="..\Contellation.Custom.Handlers\Contellation.Custom.Handlers.projitems" Label="Shared" />

  <Import Project="..\Contellation.Custom.Helpers\Contellation.Custom.Helpers.projitems" Label="Shared" />

  <Import Project="..\Contellation.Custom.Interactivities\Contellation.Custom.Interactivities.projitems" Label="Shared" />

  <Import Project="..\Contellation.Custom.Interfaces\Contellation.Custom.Interfaces.projitems" Label="Shared" />

  <Import Project="..\Contellation.Custom.Interops\Contellation.Custom.Interops.projitems" Label="Shared" />

  <Import Project="..\Contellation.Custom.Structs\Contellation.Custom.Structs.projitems" Label="Shared" />

</Project>
